/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chejdj_androiddamon_nativeCall */

#ifndef _Included_com_chejdj_androiddamon_nativeCall
#define _Included_com_chejdj_androiddamon_nativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chejdj_androiddamon_nativeCall
 * Method:    keepLiveFromnative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chejdj_androiddamon_nativeCall_keepLiveFromnative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
